name: Schedule API Call

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel API
        run: curl -X GET https://sagamonkes-sales-bot.vercel.app/api/activity
